environment_version: 1
credentials:
- type: general
  id: bUoDqWh5wKD4UP
  description: AIND Kachery Key
  value: KACHERY_CLOUD_PRIVATE_KEY
- type: general
  id: DrHQlaQDRICydt
  description: AIND Kachery Client ID
  value: KACHERY_CLOUD_CLIENT_ID
- type: general
  id: 6XlMpuMGV8Udm8
  description: AIND Kachery Zone
  value: KACHERY_ZONE
