environment_version: 1
credentials:
- type: general
  id: 6XlMpuMGV8Udm8
  description: AIND Kachery Zone
  value: KACHERY_ZONE
- type: aws
  id: MuGBmE0dHFyzxD
  description: AWS Assumable Role - aind-codeocean-power-user
  access_key_id: AWS_ACCESS_KEY_ID
  secret_access_key: AWS_SECRET_ACCESS_KEY
  region: AWS_DEFAULT_REGION
- type: general
  id: LOgUp9kKCAk0dYhd
  description: AIND Kachery API Key
  value: KACHERY_API_KEY
