#!/usr/bin/env bash
set -e

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
git checkout 2a1ecceeaa7a8d38462546feee1434b88d99836a
pip install --no-cache-dir .[full]
cd ..
