#!/usr/bin/env bash
set -e

git clone https://github.com/SpikeInterface/spikeinterface.git
cd spikeinterface
git checkout 81e53ab64b1fdafa9f7c67344502b2cf3e769512
pip install --no-cache-dir .[full]
cd ..
